// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfEvent struct {
	File    [32]int8
	Task    [16]int8
	DeltaNs uint64
	Tgid    int32
	_       [4]byte
	Dentry  uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	SecurityInodeCreate *ebpf.ProgramSpec `ebpf:"security_inode_create"`
	VfsCreate           *ebpf.ProgramSpec `ebpf:"vfs_create"`
	VfsOpen             *ebpf.ProgramSpec `ebpf:"vfs_open"`
	VfsUnlink           *ebpf.ProgramSpec `ebpf:"vfs_unlink"`
	VfsUnlinkRet        *ebpf.ProgramSpec `ebpf:"vfs_unlink_ret"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Currevent *ebpf.MapSpec `ebpf:"currevent"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	Filemap   *ebpf.MapSpec `ebpf:"filemap"`
	Start     *ebpf.MapSpec `ebpf:"start"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Currevent *ebpf.Map `ebpf:"currevent"`
	Events    *ebpf.Map `ebpf:"events"`
	Filemap   *ebpf.Map `ebpf:"filemap"`
	Start     *ebpf.Map `ebpf:"start"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Currevent,
		m.Events,
		m.Filemap,
		m.Start,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	SecurityInodeCreate *ebpf.Program `ebpf:"security_inode_create"`
	VfsCreate           *ebpf.Program `ebpf:"vfs_create"`
	VfsOpen             *ebpf.Program `ebpf:"vfs_open"`
	VfsUnlink           *ebpf.Program `ebpf:"vfs_unlink"`
	VfsUnlinkRet        *ebpf.Program `ebpf:"vfs_unlink_ret"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.SecurityInodeCreate,
		p.VfsCreate,
		p.VfsOpen,
		p.VfsUnlink,
		p.VfsUnlinkRet,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
