/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __FSYSCALL_SKEL_H__
#define __FSYSCALL_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct fsyscall {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *events;
		struct bpf_map *bss;
	} maps;
	struct {
		struct bpf_program *syscalls_sys_enter_openat;
	} progs;
	struct {
		struct bpf_link *syscalls_sys_enter_openat;
	} links;
	struct fsyscall__bss {
		struct event *unused;
	} *bss;

#ifdef __cplusplus
	static inline struct fsyscall *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct fsyscall *open_and_load();
	static inline int load(struct fsyscall *skel);
	static inline int attach(struct fsyscall *skel);
	static inline void detach(struct fsyscall *skel);
	static inline void destroy(struct fsyscall *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
fsyscall__destroy(struct fsyscall *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
fsyscall__create_skeleton(struct fsyscall *obj);

static inline struct fsyscall *
fsyscall__open_opts(const struct bpf_object_open_opts *opts)
{
	struct fsyscall *obj;
	int err;

	obj = (struct fsyscall *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = fsyscall__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	fsyscall__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct fsyscall *
fsyscall__open(void)
{
	return fsyscall__open_opts(NULL);
}

static inline int
fsyscall__load(struct fsyscall *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct fsyscall *
fsyscall__open_and_load(void)
{
	struct fsyscall *obj;
	int err;

	obj = fsyscall__open();
	if (!obj)
		return NULL;
	err = fsyscall__load(obj);
	if (err) {
		fsyscall__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
fsyscall__attach(struct fsyscall *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
fsyscall__detach(struct fsyscall *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *fsyscall__elf_bytes(size_t *sz);

static inline int
fsyscall__create_skeleton(struct fsyscall *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "fsyscall";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 2;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "events";
	s->maps[0].map = &obj->maps.events;

	s->maps[1].name = "fsyscall.bss";
	s->maps[1].map = &obj->maps.bss;
	s->maps[1].mmaped = (void **)&obj->bss;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "syscalls_sys_enter_openat";
	s->progs[0].prog = &obj->progs.syscalls_sys_enter_openat;
	s->progs[0].link = &obj->links.syscalls_sys_enter_openat;

	s->data = fsyscall__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *fsyscall__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xd8\x08\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0e\0\
\x01\0\x85\0\0\0\x0e\0\0\0\xbf\x07\0\0\0\0\0\0\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\xb7\x02\0\0\x78\0\0\0\xb7\x03\0\0\0\0\0\0\x85\0\0\0\x83\0\0\0\xbf\x06\0\0\
\0\0\0\0\x15\x06\x09\0\0\0\0\0\x77\x07\0\0\x20\0\0\0\x63\x76\0\0\0\0\0\0\xbf\
\x61\0\0\0\0\0\0\x07\x01\0\0\x04\0\0\0\xb7\x02\0\0\x50\0\0\0\x85\0\0\0\x10\0\0\
\0\xbf\x61\0\0\0\0\0\0\xb7\x02\0\0\0\0\0\0\x85\0\0\0\x84\0\0\0\xb7\0\0\0\0\0\0\
\0\x95\0\0\0\0\0\0\0\x44\x75\x61\x6c\x20\x4d\x49\x54\x2f\x47\x50\x4c\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x78\x02\0\0\x78\
\x02\0\0\x3d\x02\0\0\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\
\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x1b\0\0\0\x05\0\0\0\
\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\0\0\0\0\0\0\0\x03\0\
\0\0\0\x02\0\0\0\x04\0\0\0\0\0\0\x01\0\0\0\0\x02\0\0\x04\x10\0\0\0\x19\0\0\0\
\x01\0\0\0\0\0\0\0\x1e\0\0\0\x05\0\0\0\x40\0\0\0\x2a\0\0\0\0\0\0\x0e\x07\0\0\0\
\x01\0\0\0\0\0\0\0\0\0\0\x02\x0a\0\0\0\x31\0\0\0\x04\0\0\x04\x20\0\0\0\x3c\0\0\
\0\x0b\0\0\0\0\0\0\0\x40\0\0\0\x0b\0\0\0\x40\0\0\0\x49\0\0\0\x0b\0\0\0\x80\0\0\
\0\x4d\0\0\0\x0b\0\0\0\xc0\0\0\0\x53\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\
\0\x01\0\0\x0d\x02\0\0\0\x61\0\0\0\x09\0\0\0\x66\0\0\0\x01\0\0\x0c\x0c\0\0\0\
\xd8\x01\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x0e\0\0\
\0\x04\0\0\0\x0d\0\0\0\xdd\x01\0\0\0\0\0\x0e\x0f\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\
\x02\x12\0\0\0\0\0\0\0\0\0\0\x0a\x13\0\0\0\xe7\x01\0\0\x06\0\0\x04\x78\0\0\0\
\xed\x01\0\0\x14\0\0\0\0\0\0\0\xf1\x01\0\0\x1a\0\0\0\x20\0\0\0\x3c\0\0\0\x0b\0\
\0\0\xc0\x02\0\0\x40\0\0\0\x0b\0\0\0\0\x03\0\0\x49\0\0\0\x0b\0\0\0\x40\x03\0\0\
\x4d\0\0\0\x0b\0\0\0\x80\x03\0\0\xf6\x01\0\0\0\0\0\x08\x15\0\0\0\xfa\x01\0\0\0\
\0\0\x08\x16\0\0\0\0\x02\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\x0d\x02\0\0\0\0\0\
\x08\x18\0\0\0\x10\x02\0\0\0\0\0\x08\x19\0\0\0\x15\x02\0\0\0\0\0\x01\x01\0\0\0\
\x08\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x17\0\0\0\x04\0\0\0\x50\0\0\0\x23\x02\0\0\
\0\0\0\x0e\x11\0\0\0\x01\0\0\0\x2a\x02\0\0\x01\0\0\x0f\0\0\0\0\x1b\0\0\0\0\0\0\
\0\x08\0\0\0\x2f\x02\0\0\x01\0\0\x0f\0\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\x35\
\x02\0\0\x01\0\0\x0f\0\0\0\0\x10\0\0\0\0\0\0\0\x0d\0\0\0\0\x69\x6e\x74\0\x5f\
\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x74\
\x79\x70\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x65\x76\x65\x6e\
\x74\x73\0\x61\x6c\x6c\x6f\x63\x5f\x69\x6e\x66\x6f\0\x64\x66\x64\0\x66\x69\x6c\
\x65\x6e\x61\x6d\x65\0\x68\x6f\x77\0\x75\x73\x69\x7a\x65\0\x75\x6e\x73\x69\x67\
\x6e\x65\x64\x20\x6c\x6f\x6e\x67\0\x61\x72\x67\x73\0\x73\x79\x73\x63\x61\x6c\
\x6c\x73\x5f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\x61\x74\0\
\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x73\x79\x73\x63\x61\x6c\x6c\x73\
\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\x61\x74\0\x2f\x68\
\x6f\x6d\x65\x2f\x6a\x68\x2f\x63\x6f\x64\x65\x2f\x65\x62\x70\x66\x2d\x67\x6f\
\x2f\x65\x78\x30\x31\x2d\x73\x79\x73\x63\x61\x6c\x6c\x2d\x65\x76\x65\x6e\x74\
\x2f\x66\x73\x79\x73\x63\x61\x6c\x6c\x2e\x63\0\x09\x75\x36\x34\x20\x69\x64\x20\
\x20\x20\x3d\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\
\x5f\x70\x69\x64\x5f\x74\x67\x69\x64\x28\x29\x3b\0\x09\x74\x61\x73\x6b\x5f\x69\
\x6e\x66\x6f\x20\x3d\x20\x62\x70\x66\x5f\x72\x69\x6e\x67\x62\x75\x66\x5f\x72\
\x65\x73\x65\x72\x76\x65\x28\x26\x65\x76\x65\x6e\x74\x73\x2c\x20\x73\x69\x7a\
\x65\x6f\x66\x28\x73\x74\x72\x75\x63\x74\x20\x65\x76\x65\x6e\x74\x29\x2c\x20\
\x30\x29\x3b\0\x09\x69\x66\x20\x28\x21\x74\x61\x73\x6b\x5f\x69\x6e\x66\x6f\x29\
\x20\x7b\0\x09\x75\x33\x32\x20\x74\x67\x69\x64\x20\x3d\x20\x69\x64\x20\x3e\x3e\
\x20\x33\x32\x3b\0\x09\x74\x61\x73\x6b\x5f\x69\x6e\x66\x6f\x2d\x3e\x70\x69\x64\
\x20\x3d\x20\x74\x67\x69\x64\x3b\0\x09\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\
\x72\x72\x65\x6e\x74\x5f\x63\x6f\x6d\x6d\x28\x26\x74\x61\x73\x6b\x5f\x69\x6e\
\x66\x6f\x2d\x3e\x63\x6f\x6d\x6d\x2c\x20\x38\x30\x29\x3b\0\x09\x62\x70\x66\x5f\
\x72\x69\x6e\x67\x62\x75\x66\x5f\x73\x75\x62\x6d\x69\x74\x28\x74\x61\x73\x6b\
\x5f\x69\x6e\x66\x6f\x2c\x20\x30\x29\x3b\0\x7d\0\x63\x68\x61\x72\0\x5f\x5f\x6c\
\x69\x63\x65\x6e\x73\x65\0\x65\x76\x65\x6e\x74\0\x70\x69\x64\0\x63\x6f\x6d\x6d\
\0\x75\x33\x32\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\
\x6e\x74\0\x75\x38\0\x5f\x5f\x75\x38\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x63\
\x68\x61\x72\0\x75\x6e\x75\x73\x65\x64\0\x2e\x62\x73\x73\0\x2e\x6d\x61\x70\x73\
\0\x6c\x69\x63\x65\x6e\x73\x65\0\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\
\0\x14\0\0\0\x9c\0\0\0\xb0\0\0\0\0\0\0\0\x08\0\0\0\x80\0\0\0\x01\0\0\0\0\0\0\0\
\x0d\0\0\0\x10\0\0\0\x80\0\0\0\x09\0\0\0\0\0\0\0\xa5\0\0\0\xd9\0\0\0\x0d\xa8\0\
\0\x10\0\0\0\xa5\0\0\0\x01\x01\0\0\x0e\xb8\0\0\x40\0\0\0\xa5\0\0\0\x45\x01\0\0\
\x06\xbc\0\0\x48\0\0\0\xa5\0\0\0\x58\x01\0\0\x10\xac\0\0\x50\0\0\0\xa5\0\0\0\
\x6e\x01\0\0\x11\xcc\0\0\x58\0\0\0\xa5\0\0\0\x86\x01\0\0\x23\xd0\0\0\x68\0\0\0\
\xa5\0\0\0\x86\x01\0\0\x02\xd0\0\0\x78\0\0\0\xa5\0\0\0\xb3\x01\0\0\x02\xd4\0\0\
\x90\0\0\0\xa5\0\0\0\xd6\x01\0\0\x01\xdc\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa1\0\0\0\0\
\0\x03\0\x90\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x14\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\
\0\xa0\0\0\0\0\0\0\0\x57\0\0\0\x11\0\x06\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\
\x77\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\x81\0\0\0\x11\0\x07\0\
\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x01\0\0\0\x04\0\0\0\x58\
\x02\0\0\0\0\0\0\x04\0\0\0\x06\0\0\0\x70\x02\0\0\0\0\0\0\x04\0\0\0\x04\0\0\0\
\x88\x02\0\0\0\0\0\0\x04\0\0\0\x05\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x40\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x60\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x70\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x80\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x90\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\xa0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xb0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\xc0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x0c\x0e\x0d\0\x2e\x74\x65\x78\x74\0\x2e\
\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\x78\x74\0\x73\x79\x73\x63\x61\x6c\x6c\x73\
\x5f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\x61\x74\0\x2e\x72\
\x65\x6c\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x73\x79\x73\x63\x61\x6c\
\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x6f\x70\x65\x6e\x61\x74\0\
\x65\x76\x65\x6e\x74\x73\0\x2e\x62\x73\x73\0\x2e\x6d\x61\x70\x73\0\x2e\x6c\x6c\
\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x5f\x5f\x6c\x69\x63\x65\x6e\x73\x65\
\0\x75\x6e\x75\x73\x65\x64\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\
\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x42\x42\x30\x5f\x32\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x88\0\0\0\x03\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x2b\x08\0\0\0\0\0\0\xa8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x32\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\
\0\0\0\0\0\0\xa0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x2e\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\x07\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\x0d\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x79\
\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe0\0\0\0\0\0\0\0\x0d\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x63\0\0\0\x01\0\0\0\
\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5e\0\0\0\x08\0\0\0\x03\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x9c\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\xcd\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x98\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x58\x07\0\0\0\
\0\0\0\x30\0\0\0\0\0\0\0\x0d\0\0\0\x08\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\
\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd0\x05\0\0\0\0\0\0\xd0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x07\0\0\0\x09\
\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x88\x07\0\0\0\0\0\0\xa0\0\0\0\0\0\0\0\
\x0d\0\0\0\x0a\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x69\0\0\0\x03\x4c\xff\
\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\x28\x08\0\0\0\0\0\0\x03\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\0\0\0\x02\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xa0\x06\0\0\0\0\0\0\xa8\0\0\0\0\0\0\0\x01\0\0\0\x03\0\0\
\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct fsyscall *fsyscall::open(const struct bpf_object_open_opts *opts) { return fsyscall__open_opts(opts); }
struct fsyscall *fsyscall::open_and_load() { return fsyscall__open_and_load(); }
int fsyscall::load(struct fsyscall *skel) { return fsyscall__load(skel); }
int fsyscall::attach(struct fsyscall *skel) { return fsyscall__attach(skel); }
void fsyscall::detach(struct fsyscall *skel) { fsyscall__detach(skel); }
void fsyscall::destroy(struct fsyscall *skel) { fsyscall__destroy(skel); }
const void *fsyscall::elf_bytes(size_t *sz) { return fsyscall__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
fsyscall__assert(struct fsyscall *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
	_Static_assert(sizeof(s->bss->unused) == 8, "unexpected size of 'unused'");
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __FSYSCALL_SKEL_H__ */
