// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfArgsT struct {
	Fname uint64
	Flags int32
	_     [4]byte
}

type bpfEvent struct {
	Ts      uint64
	Pid     int32
	Uid     uint32
	Ret     int32
	Flags   int32
	Callers [2]uint64
	Comm    [16]int8
	Fname   [255]int8
	_       [1]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	SyscallsSysEnterOpen   *ebpf.ProgramSpec `ebpf:"syscalls_sys_enter_open"`
	SyscallsSysEnterOpenat *ebpf.ProgramSpec `ebpf:"syscalls_sys_enter_openat"`
	SyscallsSysExitOpen    *ebpf.ProgramSpec `ebpf:"syscalls_sys_exit_open"`
	SyscallsSysExitOpenat  *ebpf.ProgramSpec `ebpf:"syscalls_sys_exit_openat"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
	Start  *ebpf.MapSpec `ebpf:"start"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events *ebpf.Map `ebpf:"events"`
	Start  *ebpf.Map `ebpf:"start"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.Start,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	SyscallsSysEnterOpen   *ebpf.Program `ebpf:"syscalls_sys_enter_open"`
	SyscallsSysEnterOpenat *ebpf.Program `ebpf:"syscalls_sys_enter_openat"`
	SyscallsSysExitOpen    *ebpf.Program `ebpf:"syscalls_sys_exit_open"`
	SyscallsSysExitOpenat  *ebpf.Program `ebpf:"syscalls_sys_exit_openat"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.SyscallsSysEnterOpen,
		p.SyscallsSysEnterOpenat,
		p.SyscallsSysExitOpen,
		p.SyscallsSysExitOpenat,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
